In [2]:
import numpy as np

### Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет `array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]`)).

In [10]:
np.arange(9, -1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [24]:
n = 5
elements = np.arange(n, -1, -1)

diag_matrix = np.diag(elements)
diag_matrix

array([[5, 0, 0, 0, 0, 0],
       [0, 4, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0]])

In [17]:
elements.sum()

15

In [37]:
sum = 0
for row in diag_matrix:
  for cell in row:
    sum += cell
    
sum

15

In [39]:
diag_matrix.trace()

15

### Задание 3

Решите систему уравнений:
```
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3
```

In [41]:
a = np.array([[4, 1, 0], [2, 3, 5], [1, 0, 4]])
b = np.array([4, 12, -3])

np.linalg.solve(a, b)

array([-0.33333333,  5.33333333, -0.66666667])

### Задание 4

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [43]:
users_stats = np.array([
  [2, 1, 0, 0, 0, 0],
  [1, 1, 2, 1, 0, 0],
  [2, 0, 1, 0, 0, 0],
  [1, 1, 2, 1, 0, 1],
  [0, 0, 1, 2, 0, 0],
  [0, 0, 0, 0, 0, 5],
  [1, 0, 0, 0, 0, 0],
  [0, 1, 1, 0, 0, 0],
  [0, 0, 0, 1, 1, 3],
  [1, 0, 0, 2, 1, 4]], 
  np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [44]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [45]:
def cosine(a, b):
  '''
  Returns cosine between vectors
  '''
  a_length = np.linalg.norm(a)
  b_length = np.linalg.norm(b)
  
  return np.dot(a, b) / (a_length * b_length)

In [56]:
cosine_similarities = []

for user_stats in users_stats:
  cosine_similarities.append(cosine(user_stats, next_user_stats))
  
cosine_similarities

[0.19999999999999996,
 0.8451542547285165,
 0.3999999999999999,
 0.7905694150420948,
 0.3999999999999999,
 0.0,
 0.0,
 0.9486832980505138,
 0.0,
 0.0]

In [57]:
most_similar_user_index = cosine_similarities.index(max(result))
most_similar_user_index

7