In [3]:
import numpy as np

In [7]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [5]:
type(x)

numpy.ndarray

In [6]:
x.mean()

2.0

In [8]:
x + y

array([5, 7, 9])

In [9]:
x - y

array([-3, -3, -3])

In [10]:
x * y

array([ 4, 10, 18])

In [12]:
x / y

array([0.25, 0.4 , 0.5 ])

In [28]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.full(10, 1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [22]:
np.full([3, 10], 1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [26]:
a = np.arange(10)
b = np.arange(10, 20)

np.concatenate((a, b))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
import random

nums = np.arange(10)
random.shuffle(nums)

nums

array([2, 3, 1, 0, 7, 5, 9, 6, 4, 8])

### Изменение размерности

In [37]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
x.shape

(10,)

In [41]:
x.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [42]:
x.reshape(3, 3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [47]:
# транспонирование
np.array([
  [1, 2],
  [3, 4],
  [5, 6]
]).T

array([[1, 3, 5],
       [2, 4, 6]])

In [49]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x.ravel()

array([1, 2, 3, 4, 5, 6])

In [52]:
x.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [54]:
x.reshape(1, 6)

array([[1, 2, 3, 4, 5, 6]])

### Создание матриц

In [56]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
np.diag(np.arange(1, 10, 2), k=1)

array([[0, 1, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0]])

In [64]:
np.random.random(10)

array([0.3019033 , 0.35834647, 0.98920495, 0.77866741, 0.26955566,
       0.60352226, 0.50304549, 0.52261419, 0.61683203, 0.63568159])

In [69]:
np.linspace(2, 80, 17)

array([ 2.   ,  6.875, 11.75 , 16.625, 21.5  , 26.375, 31.25 , 36.125,
       41.   , 45.875, 50.75 , 55.625, 60.5  , 65.375, 70.25 , 75.125,
       80.   ])

### Скалярное произведение векторов

In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 5, 10])

np.dot(a, b)

63

### Косинусное сходство между векторами

In [9]:
def cosine(a, b):
  a_length = np.linalg.norm(a)
  b_length = np.linalg.norm(b)
  
  return np.dot(a, b) / (a_length * b_length)

In [10]:
cosine(a, b)

0.9791300486523296

### Перемножение матриц

### Линейные уравнения

In [12]:
a = np.array([[1, 3], [2, -4]])
b = np.array([9, 8])

In [13]:
np.linalg.solve(a, b)

array([6., 1.])

In [15]:
# проверка верности
np.allclose(np.dot(a, np.linalg.solve(a, b)), b)

True